### ISSUE TITLE
Nice organization so far with component files and stylesheets

### ISSUE THREAD

**Issue by Phizzard** [dickosmad/portofolio_V2#3]
<img width="365" alt="Screen Shot 2020-04-22 at 5 01 02 PM" src="https://user-images.githubusercontent.com/14220463/80033555-ee004500-84ba-11ea-9eaf-4e7482739e4f.png">

I like that you're keeping the stylesheets organized with the components and maintaining the same naming conventions (same name and casing) 👍

**Comment by dickosmad** [comment]
Thanks
