### ISSUE TITLE
Be mindful of gradients in Navbar

### ISSUE THREAD

**Issue by Phizzard** [dickosmad/portofolio_V2#4]
<img width="1355" alt="Screen Shot 2020-04-22 at 5 05 33 PM" src="https://user-images.githubusercontent.com/14220463/80033928-8991b580-84bb-11ea-8e6e-aff5c72873d4.png">

Gradients can look nice when properly used, I would recommend either dropping the gradient entirely from the navbar or changing the black to a complementary colour or an adjacent colour to create a softer look.

You may also want to be cautious of colours used in the gradient with white text for accessibility reasons to ensure the text will be readable.

**Comment by dickosmad** [comment]
Ok , it's right . 
Thanks for suggestion
