### ISSUE TITLE
Good job with the About component

### ISSUE THREAD

**Issue by Phizzard** [dickosmad/portofolio_V2#7]
<img width="1349" alt="Screen Shot 2020-04-22 at 5 17 41 PM" src="https://user-images.githubusercontent.com/14220463/80036197-4afdfa00-84bf-11ea-9bf7-2acea2a67df4.png">

I like the design choice in the about section, the only recommendations would be: 

Make sure you use a square image for the square container to avoid squishing the image.

Fix some spelling mistake with developpement (development)

Other than that - Good job! 👍

**Comment by dickosmad** [comment]
Thanks
