### ISSUE TITLE
Text colour of input labels and submit button colour low contrast.

### ISSUE THREAD

**Issue by Phizzard** [dickosmad/portofolio_V2#9]
<img width="553" alt="Screen Shot 2020-05-07 at 4 31 44 PM" src="https://user-images.githubusercontent.com/14220463/81341884-4ec57b00-9080-11ea-9365-3e472606bc3e.png">

The text is very hard to read against a darker background. I would recommend lighter colours.

**Comment by dickosmad** [comment]
Hello , fixed
